### ISSUE TITLE
Overworld Terrain Map Generation

### ISSUE THREAD

**Issue by CrossDAlex** [kyle-flynn/467-capstone#6]
Functionality to generate an overworld map based on output from the minimap. Should select the correct plate and lay them side by side in the proper orientation. Needs to have a method to render the edge of the world, either shadows/water/cliffs/etc. Does not include terrain objects such as trees, rocks, fences, etc.

**Comment by kyle-flynn** [comment]
In order to create a world, you need to create tiles, and these tiles have properties. For now, be able to make a map based upon a multidimensional array, and be able to turn those into Tile classes, and have this Tile class be modular enough so we can have different tiles such as a CityTile or WaterTile, and be able to rotate tiles, scale, etc.

**Comment by greenese** [comment]
How we've discussed this implementation:
1) Prompt to assemble dynamically sized 2d array
2) Generate overworld from texture sheet based on 2d array
3) Generate minimap from seperate texture sheet (1 pixel representations) based on 2d array
